name: Run tests
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Jest
      run: yarn add --dev jest
    - name: Run Jest tests
      run: yarn test
