name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install Jest
      run: npm install --save-dev jest
    - name: Run Jest tests
      run: jest test-test.test.js